Test login feature
CraftAcademy/rails_messaging_jan19_team2 pull request #3
Opened 2019-02-13 13:15 UTC by LauraRe

## Happy path : 
Test that user is able to login.
## Sad path : 
Test that error message is issued if user inserts wrong email or password.

2019-02-13 13:38 UTC, Joberg95 approved these changes
Good job!

2019-02-13 14:29 UTC, aleciabenjamin requested changes
no newline at end of page

2019-02-13 14:31 UTC, aleciabenjamin approved these changes

2019-02-13 14:32 UTC, perhegg approved these changes
Nice!

2019-02-14 09:01 UTC, faraznaeem requested changes

2019-02-14 09:01 UTC, faraznaeem commented on app/controllers/application_controller.rb
> +    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
Please explain what this line of code does, and why you are fixing this as this code has to do with creating a new user in the system and you are working on the login of a user?

2019-02-14 09:01 UTC, faraznaeem commented on features/login.feature
> +
remove extra line

2019-02-14 09:01 UTC, faraznaeem commented on features/login.feature
> +        When I fill in "Email" with " "
mind the indentation

2019-02-14 09:01 UTC, faraznaeem commented on features/login.feature
> +    Given I click on "Login"
Please use the same flow for all of your scenarios

2019-02-14 09:01 UTC, faraznaeem commented on features/step_definitions/basic_steps.rb
> +    visit '/'
use the rails path helper methods here, please look at the extras in the course material for more guidance

2019-02-14 09:01 UTC, faraznaeem commented on features/step_definitions/basic_steps.rb
> +        User.create!(user)
Use factory here instead

2019-02-14 09:01 UTC, faraznaeem commented on features/step_definitions/basic_steps.rb
> +    click_on(string)
don't use `string` as a variable name, and be consistent with the with the brackets

2019-02-14 09:01 UTC, faraznaeem commented on features/step_definitions/basic_steps.rb
> +    fill_in string, with: string2
choose better variable names

2019-02-14 09:02 UTC, faraznaeem commented
Update title and add a user story if you have one to the description

2019-02-14 13:37 UTC, Joberg95 approved these changes
looks good now, good job

2019-02-14 13:38 UTC, merged

2019-02-14 13:38 UTC, faraznaeem commented
Better PR title in the future, but good job

2019-02-15 08:30 UTC, aleciabenjamin reviewed
lgtm